# Server bind address
bind = "0.0.0.0:8000"

# Forward headers to upstream services.
forward_headers = []

# Receive headers from upstream service and send to client
receive_headers = []

## Optional CORS config
## If allow_any_origin is set to true it will override any origins set using the allow_origins option
# [cors]
# allow_any_origin = true
# allow_origins = ["https://example.com"]
# allow_methods = ["GET", "POST", "DELETE", "OPTIONS"]
# allow_credentials = true
# allow_headers = [
#             "Authorization",
#             "DNT",
#             "X-CustomHeader",
#             "Keep-Alive",
#             "User-Agent",
#             "X-Requested-With",
#             "If-Modified-Since",
#             "Cache-Control",
#             "Content-Type",
#         ]

# Jaeger
[jaeger]
agent_endpoint = "127.0.0.1:6831"
service_name = "graphgate"

#######################################################
## Services
#######################################################

[[services]]
name = "accounts"               # Service name
addr = "127.0.0.1:8001"         # Service address
query_path = "/"                # GraphQL query endpoint, Default: /
subscribe_path = "/"            # GraphQL subscription endpoint, Default: /
introspection_path = "/"        # GraphQL introspection path, Default: /#
websocket_path = "/"            # Endpoint to be used for graphql-transport-ws,
                                # may be different from path used for subscriptions or queries
                                # defaults to query path otherwise /

[[services]]
name = "products"
addr = "127.0.0.1:8002"

[[services]]
name = "reviews"
addr = "127.0.0.1:8003"
